#!/bin/bash
#
# build zip files from source folders, copying publish content from src/{$1}
# usage (from top of repo):
#   $ build_zip COMMIT|PUSH|WHATEVER

mkdir -p src/build/${1}

cp -p src/${1}/*.pdf src/build/${1}
cp -p src/${1}/*.png src/build/${1}
cp -p src/${1}/README.txt src/build/${1}


# copy up any presentation source files if present
cp -p src/${1}/*.pptx src/build/${1} 2>/dev/null

# copy up any worksheet source files if present
cp -p src/${1}/*.xlsx src/build/${1} 2>/dev/null

# create zip file and push it to the download zone
cd src/build
zip $(tr '[:upper:]' '[:lower:]'<<<${1})Kit.zip ${1}/*
mv $(tr '[:upper:]' '[:lower:]'<<<${1})Kit.zip ../../${1}


# push any newer files in build directory to download zone
for file in `ls ${1}`
do
  if [ ${1}/$file -nt ../../${1}/$file ];
  then
    cp ${1}/$file ../../${1}/$file
  fi
done

# clean up build directory
cd ../..
rm -rf src/build/${1}
